### ISSUE TITLE
Provider produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by juanfi** [configcat/terraform-provider-configcat#19]
### Describe the bug

We are having the following error trying to apply our infra for creating a `configcat_setting_value` resource:

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ configcat_setting_value.target_clients_setting_value, provider
│ "provider[\"registry.terraform.io/configcat/configcat\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### To reproduce

We are adding planning without any issue the following infra but we are having the error during the apply

```
resource "configcat_setting" "target_clients_flag" {
  config_id    = "config_cat_id"
  key          = "isTargetClient"
  name         = "Description"
  setting_type = "boolean"
}

resource "configcat_setting_value" "target_clients_setting_value" {
  environment_id = "config_cat_id"
  setting_id     = configcat_setting.target_clients_flag.id
  value          = "false"
  init_only      = "true"

  rollout_rules {
    comparison_attribute = "Identifier"
    comparator           = "isOneOf"
    comparison_value     = "ClientId"
    value                = "true"
  }
}
```

We are using the version 1.4.0 for the provider but we had the same issue with the 1.3.6

```
   configcat = {
      source  = "configcat/configcat"
      version = ">= 1.4"
    }

```

### Expected behavior

The resource is created

**Comment by laliconfigcat** [comment]
Hello @juanfi ,

Thanks for reaching out. I'm trying to reproduce the issue and I'll get back to you.

**Comment by laliconfigcat** [comment]
Hello @juanfi ,

I tried reproducing your issue, but it worked for me with your configuration. 
I even deleted the feature flag on the ConfigCat Dashboard after creating it with Terraform and a new terraform run could re-create it.
Could you please send me more details about your terraform files? It would be awesome if you could create a sample repository so I can reproduce your issue.  Could you please also provide the full logs for your terraform run?

**Comment by laliconfigcat** [comment]
Hello @juanfi,

Do you have any updates regarding this issue?

**Comment by juanfi** [comment]
Hi, sorry for the delay. 

I'm still having the same issue and those are the only logs that I have (We run our infra with [atlantis](https://www.runatlantis.io/) and that is the log that I have)

I'll try to replicate it in a personal project and share the repo with you if I have some free time.

Thanks.

**Comment by laliconfigcat** [comment]
Hello @juanfi,

Do you have any updates related this issue?

Cheers,
Lali

**Comment by laliconfigcat** [comment]
Hello @juanfi,

I am closing this issue as I didn't hear back from you a while ago. If you still experience the issue, please prepare a sample repository so I can reproduce the bug and try to fix it. 

Cheers,
Lali
