### ISSUE TITLE
Mandatory notes settings prevents settings value to be set/updated

### ISSUE THREAD

**Issue by easyCZ** [configcat/terraform-provider-configcat#2]
### Describe the bug

When the `Mandatory Notes` settings is enabled, a settings value cannot be set/updated through Terraform.

### To reproduce

1. Enable Mandatory Notes
2. Attempt to create a feature flag 
3. Receive `400: Reason: Required` error

### Expected behavior

As a caller, I can set the update note in Terraform.

**Comment by laliconfigcat** [comment]
Hey,

Thanks for reporting the issue, we'll add the mandatory notes to the setting value update flow.

As the ConfigCat Feature Flags Terraform Provider is quite new, it would be awesome if you could share some feedback about your experiences with it. Thanks in advance!

**Comment by laliconfigcat** [comment]
I just released v1.0.2 with the mandatory notes option. Please check if it's working for you. Any kind of feedback is much appreciated.

**Comment by easyCZ** [comment]
Hey @laliconfigcat,

Just tested the change and works. Thanks for the fix!

As for feedback, I'm still playing with my TF setup for it so will have more to share once I finish but in the meantime below are a few points.

## Getting started with Auth
Your docs point out how to inject auth credentials into the TF config (either explicitly, or through ENV vars) I spent some time getting to a setup that would work for me. I wanted the setup to auto-load the env variables when in the TF directory so went with the following:

1. I still use ENV vars, but load them from a file locally
2. I use `.envrc` and `direnv` to set the `CONFIGCAT_BASIC_AUTH_USERNAME` and `CONFIGCAT_BASIC_AUTH_PASSWORD` when entering the directory.

To make this use case simpler, it would be nice to be able to point to a file which holds the credentials and have it read the creds from there, similar to how AWS creds can be loaded through the `shared_credentials_file`

```
provider "aws" {
  region = "eu-central-1"
  shared_credentials_file = "$HOME/.aws/credentials"
  ...
}
```

## Resources usage for Product
I did not have much luck setting up the `configcat_product` as a resource in terraform. I'd get 404s from the API but I did not dig too deep, went with usage as `data` instead which is for my use case more appropriate anyway.

## Name_filter_regex
When defining an environment, it's not directly obvious how the regex should be used. Most of the examples only ever access the zero element and so the need for getting back a list of environments feels limited. In this case, I'd prefer to have the ability to get a single environment by name, instead of listing (by regex) and then picking the first element. But this is a minor thing really and may be more lack of familiarity with terraform than anything. 
```
data "configcat_environments" "develop" {
  product_id = data.configcat_products.improbable_product.products.0.product_id
  name_filter_regex = "develop"
}
``` 

## init_only for setting values
I found this setting a bit surprising. I would have either expected that the settings & values are purely managed by Terraform, or they are not managed by Terraform in a project. Based on that, any managed by terraform would always sync up the values when terraform is applied and any not managed by terraform would be ignored. But again, may be my particual use case or unfamiliarity with terraform.

**Comment by laliconfigcat** [comment]
Thanks for your feedback, really appreciate it. Continuing the discussion on Slack.
