### ISSUE TITLE
Prevent deletion of setting or config if it is not empty

### ISSUE THREAD

**Issue by ksaffarian** [configcat/terraform-provider-configcat#26]
### Is your feature request related to a problem? Please describe.

We use the provider in a multiple environment model. With every deployment of an app to each environment, a set of `settings` and `initial_values` are created.

The provider does not care if we try to define an existing `setting` or `config` multiple times. If the target exists, it basically links it to the resource.

Now, if we delete a setting in our demo deployment, it will remove that setting no matter if it has values for other environments, for example staging or live.

### Describe the solution you'd like

Upon deleting request for setting/config, the provider should check if there is any child objects in the config (i.e. other settings) or in the setting (i.e. values for other environments). If it is not empty, it should raise an error that you cannot programmatically delete the target unless all the child resources are deleted.

This prevents the config/setting from being deleted and impacts other environments.

To make this some how opt-in for user, you can enable a controlling flag in the provider configuration.

### Additional context

Add any other context about the feature request here.

**Comment by laliconfigcat** [comment]
Hello @ksaffarian ,

Thanks for reaching out. 
Could you please send us some snippets of your terraform configuration files? The provider doesn't link existing settings or configs, so it would be awesome to see how do you define your configs and settings. 
What do you mean on "we delete a setting in our demo deployment" and "if it has values for other environments"?

Cheers,
Lali

**Comment by ksaffarian** [comment]
Hey Lali
Thanks for confirming that it should not work, with existing resources.
After you said so, I went and re-checked this myself and you are right. I created this issue based on our developer experience, which I should have vetted myself first.
You can disregard this request for now. 
I believe we should follow the pattern suggested here: https://registry.terraform.io/providers/configcat/configcat/latest/docs/guides/multi_environments to make sure things work correctly.
Thanks again.
